apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    prometheus: {{ .Values.prometheusLabelValue | default .Release.Name | quote }}
    release: {{ .Release.Name }}
{{- if .Values.service.labels }}
{{ toYaml .Values.service.labels | indent 4 }}
{{- end }}
  name: {{ template "prometheus.fullname" . }}
spec:
  sessionAffinity: "{{ .Values.service.sessionAffinity }}"
  clusterIP: "{{ .Values.service.clusterIP }}"
{{- if .Values.service.externalIPs }}
  externalIPs:
{{ toYaml .Values.service.externalIPs | indent 2 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: "{{ .Values.service.loadBalancerIP }}"
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{ toYaml .Values.service.loadBalancerSourceRanges | indent 2 }}
{{- end }}
  ports:
{{- if .Values.service.ports }}
{{ toYaml .Values.service.ports | indent 2 }}
{{- else }}
  - name: http
    port: 9090
    targetPort: 9090
    protocol: TCP
{{- end }}
  selector:
    app: {{ template "prometheus.name" . }}
    {{ if empty .Values.prometheusLabelValue -}}
    prometheus: {{ template "prometheus.fullname" . }}
    {{- else -}}
    prometheus: {{ .Values.prometheusLabelValue }}
    {{- end }}
  type: "{{ .Values.service.type }}"
